_BASE_: STEPGRU_BASE.yaml
MODEL:
  OMNIGRU_CHECKPOINT_URL: 
  YOLO_CHECKPOINT_URL: /src/app/models/greene_models/yolo/bbn_yolo_M1.pt
  PRETRAINED_CHECKPOINT_URL: https://github.com/beasteers/procedural_step_recog/releases/latest/download/M1.pt
  OUTPUT_DIM: 13

SKILLS:
  - NAME: M1 - Trauma Assessment
    STEPS:
      - Optionally unclothe depending on situation.
      - Sweep* left leg.
      - Sweep* right leg.
      - Sweep* left arm.
      - Sweep* right arm.
      - Look Listen Feel Breathing.
      - Rake** chest.
      - Roll over casualty.
      - Rake the back and buttocks.
      - Check pulse.
      - Check skin temperature/quality.
      - Expose and look at chest.
      - Optionally reclothe depending on situation.
