_BASE_: STEPGRU_BASE.yaml
MODEL:
  OMNIGRU_CHECKPOINT_URL: 
  YOLO_CHECKPOINT_URL: /src/app/models/greene_models/yolo/bbn_yolo_M2.pt
  PRETRAINED_CHECKPOINT_URL: https://github.com/beasteers/procedural_step_recog/releases/latest/download/M2.pt
  OUTPUT_DIM: 8

SKILLS:
  - NAME: M2 - Apply Tourniquet
    STEPS:
    - Place tourniquet over affected extremity 2-3 inches above wound site.
    - Pull tourniquet tight.
    - Apply strap to strap body.
    - Turn windless clock wise or counter clockwise until hemorrhage is controlled.
    - Lock windless into the windless keeper.
    - Pull remaining strap over the windless keeper.
    - Secure strap and windless keeper with keeper securing device.
    - Mark time on securing device strap with permanent marker.    
