_BASE_: STEPGRU_BASE.yaml
MODEL:
  OMNIGRU_CHECKPOINT_URL: 
  YOLO_CHECKPOINT_URL: /src/app/models/greene_models/yolo/bbn_yolo_M3.pt #/src/app/models/yolo/M3.pt
  PRETRAINED_CHECKPOINT_URL: https://github.com/beasteers/procedural_step_recog/releases/latest/download/M3.pt
  OUTPUT_DIM: 5
  
SKILLS:
  - NAME: M3 - Apply pressure dressing
    STEPS:
    - Apply direct hand pressure.
    - Open dressing packaging.
    - Apply dressing with pressure point directly over wound site.
    - Wrap dressing around affected area extremity or trunk with 80 percent elastic stretch.
    - Secure dressing with securing device.
